
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pavilion
 */
public class NewHospital extends javax.swing.JFrame {

    /**
     * Creates new form NewHospital
     */
    public NewHospital() {
        initComponents();
    newHospitalPhoneText.addKeyListener(new KeyAdapter() 
        {
            public void keyTyped(KeyEvent e) 
            {
                char ch = e.getKeyChar();
                if(!isNumeric(ch) || newHospitalPhoneText.getText().length()>9)
                {
                    e.consume();
                }
            }
        });
    }

    boolean isNumeric(char c)
    {
        try 
        {
            Integer.parseInt(""+c);
            return true;
        }
        catch (Exception e) 
        {
           return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCampNameLabel = new javax.swing.JLabel();
        newCampLocationLabel = new javax.swing.JLabel();
        newCampDateLabel = new javax.swing.JLabel();
        newHospitalNameText = new javax.swing.JTextField();
        newHospitalCancelButton = new javax.swing.JButton();
        newCampCityLabel = new javax.swing.JLabel();
        newCampStateLabel = new javax.swing.JLabel();
        newHospitalCityText = new javax.swing.JTextField();
        newHospitalPhoneText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newHospitalAddressText = new javax.swing.JTextArea();
        newHospitalStateText = new javax.swing.JTextField();
        newHospitalAddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        newCampNameLabel.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        newCampNameLabel.setText("Hospital Name");
        getContentPane().add(newCampNameLabel);
        newCampNameLabel.setBounds(55, 80, 100, 33);

        newCampLocationLabel.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        newCampLocationLabel.setText("Address");
        getContentPane().add(newCampLocationLabel);
        newCampLocationLabel.setBounds(55, 160, 82, 33);

        newCampDateLabel.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        newCampDateLabel.setText("Contact No");
        getContentPane().add(newCampDateLabel);
        newCampDateLabel.setBounds(55, 350, 82, 33);
        getContentPane().add(newHospitalNameText);
        newHospitalNameText.setBounds(180, 80, 180, 33);

        newHospitalCancelButton.setText("Cancel");
        newHospitalCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newHospitalCancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newHospitalCancelButton);
        newHospitalCancelButton.setBounds(240, 400, 120, 40);

        newCampCityLabel.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        newCampCityLabel.setText("City");
        getContentPane().add(newCampCityLabel);
        newCampCityLabel.setBounds(55, 250, 82, 33);

        newCampStateLabel.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        newCampStateLabel.setText("State");
        getContentPane().add(newCampStateLabel);
        newCampStateLabel.setBounds(55, 300, 82, 33);
        getContentPane().add(newHospitalCityText);
        newHospitalCityText.setBounds(180, 250, 180, 33);
        getContentPane().add(newHospitalPhoneText);
        newHospitalPhoneText.setBounds(180, 350, 180, 33);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 43, 52));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("New Hospital");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 0, 290, 70);

        newHospitalAddressText.setColumns(20);
        newHospitalAddressText.setLineWrap(true);
        newHospitalAddressText.setRows(5);
        jScrollPane1.setViewportView(newHospitalAddressText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 130, 180, 100);
        getContentPane().add(newHospitalStateText);
        newHospitalStateText.setBounds(180, 300, 180, 33);

        newHospitalAddButton.setText("Add");
        newHospitalAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newHospitalAddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newHospitalAddButton);
        newHospitalAddButton.setBounds(50, 400, 170, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-466)/2, (screenSize.height-489)/2, 466, 489);
    }// </editor-fold>//GEN-END:initComponents

    private void newHospitalCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newHospitalCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_newHospitalCancelButtonActionPerformed

    private void newHospitalAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newHospitalAddButtonActionPerformed
        String name = newHospitalNameText.getText();
        String address = newHospitalAddressText.getText();
        String city = newHospitalCityText.getText();
        String state = newHospitalStateText.getText();
        String phone = newHospitalPhoneText.getText();

        if (name.isEmpty() || address.isEmpty() || city.isEmpty() || state.isEmpty() || phone.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "All fields mandatory !!");
        }
        else if(phone.length()<10)
        {
            JOptionPane.showMessageDialog(this, "Phone number not valid");
        }
        else 
        {
            try
            {
                
                Connection con = DataBaseConnection.open();
                Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                ResultSet rs = stmt.executeQuery("select * from hospital");
                rs.moveToInsertRow();
                rs.updateString("hospital_name", name);
                rs.updateString("hospital_address", address);
                rs.updateString("hospital_city", city);
                rs.updateString("hospital_state", state);
                rs.updateString("hospital_phone", phone);
                rs.insertRow();
                JOptionPane.showMessageDialog(this, "Hospital Added Sucessfully!!");
                newHospitalAddressText.setText("");
                newHospitalNameText.setText("");
                newHospitalCityText.setText("");
                newHospitalPhoneText.setText("");
                newHospitalStateText.setText("");
                DataBaseConnection.close(con);
            } 
            catch (Exception ex) 
            {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_newHospitalAddButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Global.mainForm.setEnabled(true);
        Global.mainForm.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewHospital().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newCampCityLabel;
    private javax.swing.JLabel newCampDateLabel;
    private javax.swing.JLabel newCampLocationLabel;
    private javax.swing.JLabel newCampNameLabel;
    private javax.swing.JLabel newCampStateLabel;
    private javax.swing.JButton newHospitalAddButton;
    private javax.swing.JTextArea newHospitalAddressText;
    private javax.swing.JButton newHospitalCancelButton;
    private javax.swing.JTextField newHospitalCityText;
    private javax.swing.JTextField newHospitalNameText;
    private javax.swing.JTextField newHospitalPhoneText;
    private javax.swing.JTextField newHospitalStateText;
    // End of variables declaration//GEN-END:variables
}
